### ISSUE TITLE
Small issue with the target blank

### ISSUE THREAD

**Issue by mbiesiad** [PresearchOfficial/Start-Extension-Chrome#4]
Hi. First of all, great work!

Not a big deal, but at this moment there is:
![image](https://user-images.githubusercontent.com/18367606/154066415-516c2e4a-551c-49f2-be20-eab8e4dd892a.png)
and next, there is also:
![image](https://user-images.githubusercontent.com/18367606/154066496-dfdc8318-d2b5-4173-afe9-a5ec883787ae.png)

Both of the chars are usually very close to each others on the keyboard (ie. QWERTY type). I suppose, that's the reason.

PR with solution/fixes:
#3 

It is worth emphasizing that <kbd>target="_blank"</kbd> behaves differently than <kbd>target="blank"</kbd> (as at this moment), so the slightly present behavior is also corrected.

Best wishes,
Michal

**Comment by jejopl** [comment]
Fixed by @mbiesiad - thanks! :-)

**Comment by mbiesiad** [comment]
My pleasure! 🎉 Best wishes
